### ISSUE TITLE
SecondStage minMax  

### ISSUE THREAD

**Issue by znesic** [CANFLUX/Calculation_Procedures#19]
This parameter seems to be needed only for the syntax checks. It is not being used for the cleaning. Either remove the syntax requirement or apply the min/max criteria for the cleaning.

**Comment by June-Skeeter** [comment]
On lines 78-97 in Biomet.net\matlab\TRACEANALYSIS_FIRSTSTAGE\read_ini_file.m, replacing:

`required_common_ini_fields = {'variableName', 'title', 'units', 'minMax'}; 
required_first_stage_ini_fields = {'inputFileName', 'measurementType'};`

with:

`required_common_ini_fields = {'variableName', 'title', 'units'}; 
required_first_stage_ini_fields = {'inputFileName', 'measurementType', 'minMax'};`

will fix the behaviour.  If there are some select scenarios where re-applying the minMax could be desired (calculating a new variable in stage 2).  Then the test could be: 1) coded into with the eval statement without requiring any change to the current procedures or given as an optional parameter that only executes if present (which may require further changes to procedures).

**Comment by znesic** [comment]
Done
