### ISSUE TITLE
Wrong repo name?

### ISSUE THREAD

**Issue by znesic** [CANFLUX/Calculation_Procedures#7]
I think that this entire repo should go under name Calculation_Procedures because that's the folder where these files go. Does it make sense to do that? What are possible drawbacks of doing this?

**Comment by June-Skeeter** [comment]
Sorry for the late reply - it shouldn't cause issues - git should automatically update the name in local repos.  Any external links (e.g. from a google doc) will just need to be changed from TraceAnalysis_ini to Calculation_Procedures
